# Generated by Django 4.1.5 on 2023-02-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_expenses_budget_amount_currency_alter_budget_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
