# Generated by Django 4.1.6 on 2023-02-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_expenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main_app.budget'),
        ),
    ]
